server:
  servlet:
    context-path: /
  port: 9999
  tomcat:
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=java5_foodmart;encrypt=false;trustServerCertificate=True
    username: sa
    password: Sa@123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
cloudinary:
  cloud-name: ddo8dn17e
  api-key: 439854322171673
  api-secret: um5uZAA2AHCSHdCLSUcGPUyDZHA




