server:
  servlet:
    context-path: /
  port: 9999
  tomcat:
    max-http-form-post-size: 20MB

spring:
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=java5_foodmart;encrypt=false;trustServerCertificate=True
    username: sa
    password: Sa@123456789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
cloudinary:
  cloud-name: ddo8dn17e
  api-key: 439854322171673
  api-secret: um5uZAA2AHCSHdCLSUcGPUyDZHA
PAYOS_CLIENT_ID: 127b6dae-5447-4043-836d-9b43e982a366
PAYOS_API_KEY: e646278f-dfb1-4c48-8ba8-7bf5b6d9bf7b
PAYOS_CHECKSUM_KEY: 0316cf13989613ab16b19538a82df429340017ca1c3aae8375e677a4f90385db




